name: CI

on: [push, pull_request]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        version: ['5.15.0']
        build_type: ['Release', 'Debug']

    steps:
      - uses: actions/checkout@v2

      - uses: lukka/get-cmake@latest

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/Qt-${{ runner.os }}-${{ matrix.version }}
          key: ${{ runner.os }}-QtCache-${{ matrix.version }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.version }}
          dir: ${{ github.workspace }}/Qt-${{ runner.os }}-${{ matrix.version }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Configure NetUdp
        run: |
          mkdir -p build
          cmake -DNETUDP_ENABLE_EXAMPLES=ON -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" -B build -S .
        shell: bash

      - name: Build NetUdp
        run: |
          cmake --build build --target "NetUdp" --config "${{ matrix.build_type }}" -j

      - name: Build Examples
        run: |
          cmake --build build --target "NetUdp_EchoClient" --config "${{ matrix.build_type }}" -j
          cmake --build build --target "NetUdp_EchoServer" --config "${{ matrix.build_type }}" -j
          cmake --build build --target "NetUdp_EchoClientServer" --config "${{ matrix.build_type }}" -j
          cmake --build build --target "NetUdp_EchoMulticastLoopback" --config "${{ matrix.build_type }}"